### ISSUE TITLE
Incompatible mod set

### ISSUE THREAD

**Issue by HacerAE** [Wurst-Imperium/WI-Zoom#30]
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install fabric, version 0.57.3 or later.
Unmet dependency listing:
	 - Mod 'WI Zoom' (wi_zoom) 1.4-MC1.19.2 requires version 0.57.3 or later of fabric, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
- Install fabric, version 0.57.3 or later.
- Unmet dependency listing:
- Mod 'WI Zoom' (wi_zoom) 1.4-MC1.19.2 requires version 0.57.3 or later of fabric, which is missing!

How do I fix this???

**Comment by omerien** [comment]
When Fabric asks you to install Fabric, it's talking about the Fabric API (https://www.curseforge.com/minecraft/mc-mods/fabric-api)

**Comment by Alexander01998** [comment]
Hi @HacerAE,

The error message you're encountering is because you're currently missing the Fabric API, which is required for WI Zoom to work correctly.

As the error message suggests, you need to install Fabric API version 0.57.3 or later. But more specifically, you will need a Fabric API version meant for Minecraft 1.19.2.

Here is a list of Fabric API version you can use, with download links: https://modrinth.com/mod/fabric-api/versions?g=1.19.2

Hope this helps! Let me know if you encounter any further problems.
