### ISSUE TITLE
Cant Remove Mod.

### ISSUE THREAD

**Issue by MasterAli2** [Wurst-Imperium/WI-Zoom#39]
i have instaled teh mod using Tlaunchers mod menu (Az client modpack) and eachtime i remove it from mods foder it reapears on game lauch

**Comment by Alexander01998** [comment]
Hey @MasterAli2,

Thanks for reaching out. WI-Zoom itself doesn't have any features to automatically reinstall itself after being removed from the mods folder. (Check the source code if you don't believe me.) Since you mentioned that you installed it using TLauncher's mod menu, it's possible that TLauncher has some kind of built-in mechanism that automatically restores the mod.

In this case, I would recommend reaching out to the TLauncher developers for assistance. They would have a better understanding of how their modpack system works and can provide you with the necessary guidance to properly remove the mod.
